### ISSUE TITLE
UML Diagrams

### ISSUE THREAD

**Issue by KonstantinPronin** [KostadinAlmishev/task-manager#10]
Продумать взаимодействие компонент, разхраблотать UML диаграммы

**Comment by KostadinAlmishev** [comment]
Предлагаю [UML](https://www.quickdatabasediagrams.com/)

**Comment by KonstantinPronin** [comment]
Приложение не подходит, там можно только связи между таблицами для БД делать (как я понял),
предлагаю использовать [draw.io](https://www.draw.io)
